arch: s390x
services:
  - docker
script: 
    docker build -t aspnetcalenderapp -f Dockerfile .
before_deploy:
    - docker tag  aspnetcalenderapp  "$DOCKER_USERNAME"/aspnetcalenderapptravis:latest
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
deploy:
  provider: script
  script: 
     docker push "$DOCKER_USERNAME"/aspnetcalenderapptravis:latest
  on:
    branch: master  
    
